
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shashank915/spring-cloud-configuration
          search-paths: limits-service,currency-exchange-service,currency-convertor-service,eureka-naming-server
server:
  port: 8888